package model;
// Generated 7 janv. 2020 21:01:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ActionUserId generated by hbm2java
 */
public class ActionUserId  implements java.io.Serializable {


     private BigDecimal idUser;
     private BigDecimal idAnnonce;
     private String dateActionUser;
     private String heureActionUser;

    public ActionUserId() {
    }

    public ActionUserId(BigDecimal idUser, BigDecimal idAnnonce, String dateActionUser, String heureActionUser) {
       this.idUser = idUser;
       this.idAnnonce = idAnnonce;
       this.dateActionUser = dateActionUser;
       this.heureActionUser = heureActionUser;
    }
   
    public BigDecimal getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(BigDecimal idUser) {
        this.idUser = idUser;
    }
    public BigDecimal getIdAnnonce() {
        return this.idAnnonce;
    }
    
    public void setIdAnnonce(BigDecimal idAnnonce) {
        this.idAnnonce = idAnnonce;
    }
    public String getDateActionUser() {
        return this.dateActionUser;
    }
    
    public void setDateActionUser(String dateActionUser) {
        this.dateActionUser = dateActionUser;
    }
    public String getHeureActionUser() {
        return this.heureActionUser;
    }
    
    public void setHeureActionUser(String heureActionUser) {
        this.heureActionUser = heureActionUser;
    }




}


