package model;
// Generated 7 janv. 2020 21:01:58 by Hibernate Tools 4.3.1



/**
 * ActionEmp generated by hbm2java
 */
public class ActionEmp  implements java.io.Serializable {


     private ActionEmpId id;
     private Annonce annonce;
     private Employe employe;
     private String libelleActionEmp;
     private String motifActionEmp;

    public ActionEmp() {
    }

	
    public ActionEmp(ActionEmpId id, Annonce annonce, Employe employe) {
        this.id = id;
        this.annonce = annonce;
        this.employe = employe;
    }
    public ActionEmp(ActionEmpId id, Annonce annonce, Employe employe, String libelleActionEmp, String motifActionEmp) {
       this.id = id;
       this.annonce = annonce;
       this.employe = employe;
       this.libelleActionEmp = libelleActionEmp;
       this.motifActionEmp = motifActionEmp;
    }
   
    public ActionEmpId getId() {
        return this.id;
    }
    
    public void setId(ActionEmpId id) {
        this.id = id;
    }
    public Annonce getAnnonce() {
        return this.annonce;
    }
    
    public void setAnnonce(Annonce annonce) {
        this.annonce = annonce;
    }
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }
    public String getLibelleActionEmp() {
        return this.libelleActionEmp;
    }
    
    public void setLibelleActionEmp(String libelleActionEmp) {
        this.libelleActionEmp = libelleActionEmp;
    }
    public String getMotifActionEmp() {
        return this.motifActionEmp;
    }
    
    public void setMotifActionEmp(String motifActionEmp) {
        this.motifActionEmp = motifActionEmp;
    }




}


