package model;
// Generated 26 d�c. 2019 00:47:10 by Hibernate Tools 4.3.1


import dao.ActionEmpDao;
import dao.PhotoDao;
import dao.VoitureDao;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Annonce generated by hbm2java
 */
public class Annonce  implements java.io.Serializable {


     private BigDecimal idAnnonce;
     private UtilisateurConnecte utilisateurConnecte;
     private String titreAnnonce;
     private String dateDepotAnnonce;
     private String heureDepotAnnonce;
     private String categorie;
     private String souscategorie;
     private BigDecimal prixAnnonce;
     private String typeAnnonce;
     private String descriptionAnnonce;
     private String villeAnnonce;
     private String dateExpirationAnnonce;
     private BigDecimal nbVueAnnonce;
     private String etatAnnonce;
     private String ipAnnonce;
     private String paysAnnonce;
     private String noteAnnonce;
     private String degreNoteAnnonce;
     private Set actionEmps = new HashSet(0);
     private Set maisonVillas = new HashSet(0);
     private Set modificationsForIdAnnonceOld = new HashSet(0);
     private Set modificationsForIdAnnonceNew = new HashSet(0);
     private Set voitures = new HashSet(0);
     private Set doublantsForIdAnnonce1 = new HashSet(0);
     private Set motos = new HashSet(0);
     private Set doublantsForIdAnnonce2 = new HashSet(0);
     private Set actionUsers = new HashSet(0);
     private Set reclamations = new HashSet(0);
     private Set autreImmobiliers = new HashSet(0);
     private Set photos = new HashSet(0);
     private Set favorises = new HashSet(0);
  private String cheminFirst;
  private String motiRejet;
     private List<String> Chemins;
     private boolean fav;
     private int nbFav; 

    public int getNbFav() {
        return nbFav;
    }

    public void setNbFav(int nbFav) {
        this.nbFav = nbFav;
    }

    public boolean isFav() {
        return fav;
    }

    public void setFav(boolean fav) {
        this.fav = fav;
    }
     
    public void setChemins(List<String> Chemins) {
        this.Chemins = Chemins;
    }

    public String getMotiRejet() {
        ActionEmpDao empDao=new ActionEmpDao();
        ActionEmp actEmp=empDao.getActionEmpRejetByAnnonce(this);
        if(actEmp!=null){
             motiRejet=actEmp.getMotifActionEmp();
        }else
        {
            motiRejet="";
        }
       
        
        return motiRejet;
    }

    public String getCheminFirst() {
        PhotoDao PDA=new PhotoDao();
         List<String> P= PDA.getPhotosByIdAnnChemn(idAnnonce);
        if(!P.isEmpty()){
         String c1=P.get(0);
        String[] c=c1.split("/");
       cheminFirst=c[c.length-1];} 
        else{
            cheminFirst="c.png";
        }
    return cheminFirst;
    }
        
public List<String>  getChemins() {
       PhotoDao PDA=new PhotoDao();
         List<String> F=new ArrayList<>();
         List<String> P= PDA.getPhotosByIdAnnChemn(idAnnonce);
        if(!P.isEmpty()){
            for (String e : P) {
                  String[] c=e.split("/");
                   cheminFirst=c[c.length-1]; 
        F.add(cheminFirst);
             }
        }
        return F;  
         }
   

    public void setCheminFirst(String cheminFirst) {
        this.cheminFirst = cheminFirst;
    }
 
    public Annonce() {
    }

 
	
    public Annonce(BigDecimal idAnnonce) {
        this.idAnnonce = idAnnonce;
    }
    public Annonce(BigDecimal idAnnonce, UtilisateurConnecte utilisateurConnecte, String titreAnnonce, String dateDepotAnnonce, String heureDepotAnnonce, String categorie, String souscategorie, BigDecimal prixAnnonce, String typeAnnonce, String descriptionAnnonce, String villeAnnonce, String dateExpirationAnnonce, BigDecimal nbVueAnnonce, String etatAnnonce, String ipAnnonce, String paysAnnonce, Set actionEmps, Set maisonVillas, Set modificationsForIdAnnonceOld, Set modificationsForIdAnnonceNew, Set voitures, Set doublantsForIdAnnonce1, Set motos, Set doublantsForIdAnnonce2, Set actionUsers, Set reclamations, Set autreImmobiliers, Set photos, Set favorises) {
       this.idAnnonce = idAnnonce;
       this.utilisateurConnecte = utilisateurConnecte;
       this.titreAnnonce = titreAnnonce;
       this.dateDepotAnnonce = dateDepotAnnonce;
       this.heureDepotAnnonce = heureDepotAnnonce;
       this.categorie = categorie;
       this.souscategorie = souscategorie;
       this.prixAnnonce = prixAnnonce;
       this.typeAnnonce = typeAnnonce;
       this.descriptionAnnonce = descriptionAnnonce;
       this.villeAnnonce = villeAnnonce;
       this.dateExpirationAnnonce = dateExpirationAnnonce;
       this.nbVueAnnonce = nbVueAnnonce;
       this.etatAnnonce = etatAnnonce;
       this.ipAnnonce = ipAnnonce;
       this.paysAnnonce = paysAnnonce;
       this.actionEmps = actionEmps;
       this.maisonVillas = maisonVillas;
       this.modificationsForIdAnnonceOld = modificationsForIdAnnonceOld;
       this.modificationsForIdAnnonceNew = modificationsForIdAnnonceNew;
       this.voitures = voitures;
       this.doublantsForIdAnnonce1 = doublantsForIdAnnonce1;
       this.motos = motos;
       this.doublantsForIdAnnonce2 = doublantsForIdAnnonce2;
       this.actionUsers = actionUsers;
       this.reclamations = reclamations;
       this.autreImmobiliers = autreImmobiliers;
       this.photos = photos;
       this.favorises = favorises;
    }
   
    public BigDecimal getIdAnnonce() {
        return this.idAnnonce;
    }
    
    public void setIdAnnonce(BigDecimal idAnnonce) {
        this.idAnnonce = idAnnonce;
    }
    public UtilisateurConnecte getUtilisateurConnecte() {
        return this.utilisateurConnecte;
    }
    
    public void setUtilisateurConnecte(UtilisateurConnecte utilisateurConnecte) {
        this.utilisateurConnecte = utilisateurConnecte;
    }
    public String getTitreAnnonce() {
        return this.titreAnnonce;
    }
    
    public void setTitreAnnonce(String titreAnnonce) {
        this.titreAnnonce = titreAnnonce;
    }
    public String getDateDepotAnnonce() {
        return this.dateDepotAnnonce;
    }
    
    public void setDateDepotAnnonce(String dateDepotAnnonce) {
        this.dateDepotAnnonce = dateDepotAnnonce;
    }
    public String getHeureDepotAnnonce() {
        return this.heureDepotAnnonce;
    }
    
    public void setHeureDepotAnnonce(String heureDepotAnnonce) {
        this.heureDepotAnnonce = heureDepotAnnonce;
    }
    public String getCategorie() {
        return this.categorie;
    }
    
    public void setCategorie(String categorie) {
        this.categorie = categorie;
    }
    public String getSouscategorie() {
        return this.souscategorie;
    }
    
    public void setSouscategorie(String souscategorie) {
        this.souscategorie = souscategorie;
    }
    public BigDecimal getPrixAnnonce() {
        return this.prixAnnonce;
    }
    
    public void setPrixAnnonce(BigDecimal prixAnnonce) {
        this.prixAnnonce = prixAnnonce;
    }
    public String getTypeAnnonce() {
        return this.typeAnnonce;
    }
    
    public void setTypeAnnonce(String typeAnnonce) {
        this.typeAnnonce = typeAnnonce;
    }
    public String getDescriptionAnnonce() {
        return this.descriptionAnnonce;
    }

    public String getDegreNoteAnnonce() {
        return degreNoteAnnonce;
    }

    public void setDegreNoteAnnonce(String degreNoteAnnonce) {
        this.degreNoteAnnonce = degreNoteAnnonce;
    }
    
    public void setDescriptionAnnonce(String descriptionAnnonce) {
        this.descriptionAnnonce = descriptionAnnonce;
    }
    public String getVilleAnnonce() {
        return this.villeAnnonce;
    }
    
    public void setVilleAnnonce(String villeAnnonce) {
        this.villeAnnonce = villeAnnonce;
    }
    public String getDateExpirationAnnonce() {
        return this.dateExpirationAnnonce;
    }
    
    public void setDateExpirationAnnonce(String dateExpirationAnnonce) {
        this.dateExpirationAnnonce = dateExpirationAnnonce;
    }
    public BigDecimal getNbVueAnnonce() {
        return this.nbVueAnnonce;
    }
    
    public void setNbVueAnnonce(BigDecimal nbVueAnnonce) {
        this.nbVueAnnonce = nbVueAnnonce;
    }
    public String getEtatAnnonce() {
        return this.etatAnnonce;
    }
    
    public void setEtatAnnonce(String etatAnnonce) {
        this.etatAnnonce = etatAnnonce;
    }
    public String getIpAnnonce() {
        return this.ipAnnonce;
    }
    
    public void setIpAnnonce(String ipAnnonce) {
        this.ipAnnonce = ipAnnonce;
    }
    public String getPaysAnnonce() {
        return this.paysAnnonce;
    }
    
    public void setPaysAnnonce(String paysAnnonce) {
        this.paysAnnonce = paysAnnonce;
    }
    public Set getActionEmps() {
        return this.actionEmps;
    }

    public String getNoteAnnonce() {
        return noteAnnonce;
    }

    public void setNoteAnnonce(String noteAnnonce) {
        this.noteAnnonce = noteAnnonce;
    }
    
    public void setActionEmps(Set actionEmps) {
        this.actionEmps = actionEmps;
    }
    public Set getMaisonVillas() {
        return this.maisonVillas;
    }
    
    public void setMaisonVillas(Set maisonVillas) {
        this.maisonVillas = maisonVillas;
    }
    public Set getModificationsForIdAnnonceOld() {
        return this.modificationsForIdAnnonceOld;
    }
    
    public void setModificationsForIdAnnonceOld(Set modificationsForIdAnnonceOld) {
        this.modificationsForIdAnnonceOld = modificationsForIdAnnonceOld;
    }
    public Set getModificationsForIdAnnonceNew() {
        return this.modificationsForIdAnnonceNew;
    }
    
    public void setModificationsForIdAnnonceNew(Set modificationsForIdAnnonceNew) {
        this.modificationsForIdAnnonceNew = modificationsForIdAnnonceNew;
    }
    public Set getVoitures() {
        return this.voitures;
    }
    
    public void setVoitures(Set voitures) {
        this.voitures = voitures;
    }
    public Set getDoublantsForIdAnnonce1() {
        return this.doublantsForIdAnnonce1;
    }
    
    public void setDoublantsForIdAnnonce1(Set doublantsForIdAnnonce1) {
        this.doublantsForIdAnnonce1 = doublantsForIdAnnonce1;
    }
    public Set getMotos() {
        return this.motos;
    }
    
    public void setMotos(Set motos) {
        this.motos = motos;
    }
    public Set getDoublantsForIdAnnonce2() {
        return this.doublantsForIdAnnonce2;
    }
    
    public void setDoublantsForIdAnnonce2(Set doublantsForIdAnnonce2) {
        this.doublantsForIdAnnonce2 = doublantsForIdAnnonce2;
    }
    public Set getActionUsers() {
        return this.actionUsers;
    }
    
    public void setActionUsers(Set actionUsers) {
        this.actionUsers = actionUsers;
    }
    public Set getReclamations() {
        return this.reclamations;
    }
    
    public void setReclamations(Set reclamations) {
        this.reclamations = reclamations;
    }
    public Set getAutreImmobiliers() {
        return this.autreImmobiliers;
    }
    
    public void setAutreImmobiliers(Set autreImmobiliers) {
        this.autreImmobiliers = autreImmobiliers;
    }
    public Set getPhotos() {
             
      
        return this.photos;
    }
    
    public void setPhotos(Set photos) {
        this.photos = photos;
    }
    public Set getFavorises() {
        return this.favorises;
    }
    
    public void setFavorises(Set favorises) {
        this.favorises = favorises;
    }

 


}


