package model;
// Generated 7 janv. 2020 21:01:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * AppartementBureau generated by hbm2java
 */
public class AppartementBureau  implements java.io.Serializable {


     private BigDecimal idAppartement;
     private MaisonVilla maisonVilla;
     private BigDecimal etageAppartement;
     private String usage;

    public AppartementBureau() {
    }

    public AppartementBureau(MaisonVilla maisonVilla, BigDecimal etageAppartement, String usage) {
       this.maisonVilla = maisonVilla;
       this.etageAppartement = etageAppartement;
       this.usage = usage;
    }
   
    public BigDecimal getIdAppartement() {
        return this.idAppartement;
    }
    
    public void setIdAppartement(BigDecimal idAppartement) {
        this.idAppartement = idAppartement;
    }
    public MaisonVilla getMaisonVilla() {
        return this.maisonVilla;
    }
    
    public void setMaisonVilla(MaisonVilla maisonVilla) {
        this.maisonVilla = maisonVilla;
    }
    public BigDecimal getEtageAppartement() {
        return this.etageAppartement;
    }
    
    public void setEtageAppartement(BigDecimal etageAppartement) {
        this.etageAppartement = etageAppartement;
    }
    public String getUsage() {
        return this.usage;
    }
    
    public void setUsage(String usage) {
        this.usage = usage;
    }




}


