package model;
// Generated 7 janv. 2020 21:01:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * AutreImmobilier generated by hbm2java
 */
public class AutreImmobilier  implements java.io.Serializable {


     private BigDecimal idAutreImmobilier;
     private Annonce annonce;
     private String emplacementAutreImmobilier;
     private BigDecimal superficieAutreImmobilier;
     private BigDecimal prixMcAutreImmobilier;
     private Set terrainFermes = new HashSet(0);

    public AutreImmobilier() {
    }

    public AutreImmobilier(Annonce annonce, String emplacementAutreImmobilier, BigDecimal superficieAutreImmobilier, BigDecimal prixMcAutreImmobilier, Set terrainFermes) {
       this.annonce = annonce;
       this.emplacementAutreImmobilier = emplacementAutreImmobilier;
       this.superficieAutreImmobilier = superficieAutreImmobilier;
       this.prixMcAutreImmobilier = prixMcAutreImmobilier;
       this.terrainFermes = terrainFermes;
    }
   
    public BigDecimal getIdAutreImmobilier() {
        return this.idAutreImmobilier;
    }
    
    public void setIdAutreImmobilier(BigDecimal idAutreImmobilier) {
        this.idAutreImmobilier = idAutreImmobilier;
    }
    public Annonce getAnnonce() {
        return this.annonce;
    }
    
    public void setAnnonce(Annonce annonce) {
        this.annonce = annonce;
    }
    public String getEmplacementAutreImmobilier() {
        return this.emplacementAutreImmobilier;
    }
    
    public void setEmplacementAutreImmobilier(String emplacementAutreImmobilier) {
        this.emplacementAutreImmobilier = emplacementAutreImmobilier;
    }
    public BigDecimal getSuperficieAutreImmobilier() {
        return this.superficieAutreImmobilier;
    }
    
    public void setSuperficieAutreImmobilier(BigDecimal superficieAutreImmobilier) {
        this.superficieAutreImmobilier = superficieAutreImmobilier;
    }
    public BigDecimal getPrixMcAutreImmobilier() {
        return this.prixMcAutreImmobilier;
    }
    
    public void setPrixMcAutreImmobilier(BigDecimal prixMcAutreImmobilier) {
        this.prixMcAutreImmobilier = prixMcAutreImmobilier;
    }
    public Set getTerrainFermes() {
        return this.terrainFermes;
    }
    
    public void setTerrainFermes(Set terrainFermes) {
        this.terrainFermes = terrainFermes;
    }




}


