package model;
// Generated 17 juil. 2019 09:12:32 by Hibernate Tools 4.3.1


import dao.MessageDao;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set; 

/**
 * Chat generated by hbm2java
 */
public class Chat  implements java.io.Serializable{


     private BigDecimal idChat;
     private UtilisateurConnecte utilisateurConnecte;
     private UtilisateurConnecte contact;
     private String etiquettePhoto;
     private String etiquette;
    // private Message 
     private String lastMessage;
     private String dateLastMessage;
     private String  etatLastMsg;
     private BigDecimal idRecepLast;
     private int nbMessageNonLu;
      private Set messages = new HashSet(0);

    public int getNbMessageNonLu() {
       
          return nbMessageNonLu;
    }

    public void setNbMessageNonLu(int nbMessageNonLu) {
        this.nbMessageNonLu = nbMessageNonLu;
    }

    public String getLastMessage() {
        return lastMessage;
    }

    public void setLastMessage(String lastMessage) {
        this.lastMessage = lastMessage;
    }

    public String getDateLastMessage() {
        return dateLastMessage;
    }

    public void setDateLastMessage(String dateLastMessage) {
        this.dateLastMessage = dateLastMessage;
    }
    
 
  /*
    public Message getLastMessage() {
        
         MessageDao mdao=new MessageDao();
         BigDecimal id=mdao.lastMessage(this);
         Message ms=mdao.getById(id);
        return ms;
    }

    public void setLastMessage(Message lastMessage) {
        this.lastMessage = lastMessage;
    }*/
     public String getEtiquettePhoto() {
        return etiquettePhoto;
    }

    public void setEtiquettePhoto(String etiquettePhoto) {
        this.etiquettePhoto = etiquettePhoto;
    }

    public String getEtatLastMsg() {
        return etatLastMsg;
    }

    public void setEtatLastMsg(String etatLastMsg) {
        this.etatLastMsg = etatLastMsg;
    }

    public BigDecimal getIdRecepLast() {
        return idRecepLast;
    }

    public void setIdRecepLast(BigDecimal idRecepLast) {
        this.idRecepLast = idRecepLast;
    }
   

    public String getEtiquette() {
       
        
        return etiquette;
    }

    public void setEtiquette(String etiquette) {
        this.etiquette = etiquette;
    }
      

    public UtilisateurConnecte getContact() {
        return contact;
    }

    public void setContact(UtilisateurConnecte contact) {
        this.contact = contact;
    }
    

    public Chat() {
    }

	
    public Chat(BigDecimal idChat) {
        this.idChat = idChat;
    }
    public Chat(BigDecimal idChat, UtilisateurConnecte utilisateurConnecte, Set messages) {
       this.idChat = idChat;
       this.utilisateurConnecte = utilisateurConnecte;
       this.messages = messages;
    }
   
    public BigDecimal getIdChat() {
        return this.idChat;
    }
    
    public void setIdChat(BigDecimal idChat) {
        this.idChat = idChat;
    }
    public UtilisateurConnecte getUtilisateurConnecte() {
        return this.utilisateurConnecte;
    }
    
    public void setUtilisateurConnecte(UtilisateurConnecte utilisateurConnecte) {
        this.utilisateurConnecte = utilisateurConnecte;
    }
    public Set getMessages() {
         
        return this.messages;
    }
    
    public void setMessages(Set messages) {
        this.messages = messages;
    }

   



}


