package model;
// Generated 7 janv. 2020 21:01:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DoublantId generated by hbm2java
 */
public class DoublantId  implements java.io.Serializable {


     private BigDecimal idAnnonce1;
     private BigDecimal idAnnonce2;

    public DoublantId() {
    }

    public DoublantId(BigDecimal idAnnonce1, BigDecimal idAnnonce2) {
       this.idAnnonce1 = idAnnonce1;
       this.idAnnonce2 = idAnnonce2;
    }
   
    public BigDecimal getIdAnnonce1() {
        return this.idAnnonce1;
    }
    
    public void setIdAnnonce1(BigDecimal idAnnonce1) {
        this.idAnnonce1 = idAnnonce1;
    }
    public BigDecimal getIdAnnonce2() {
        return this.idAnnonce2;
    }
    
    public void setIdAnnonce2(BigDecimal idAnnonce2) {
        this.idAnnonce2 = idAnnonce2;
    }




}


