package model;
// Generated 7 janv. 2020 21:01:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Doublant generated by hbm2java
 */
public class Doublant  implements java.io.Serializable {


     private DoublantId id;
     private Annonce annonceByIdAnnonce1;
     private Annonce annonceByIdAnnonce2;
     private BigDecimal pourcentageTitreDoublant;
     private BigDecimal pourcentageCategorieDoublant;
     private BigDecimal pourcentagePhotoDoublant;
     private BigDecimal pourcentageTexteDoublant;

    public Doublant() {
    }

	
    public Doublant(DoublantId id, Annonce annonceByIdAnnonce1, Annonce annonceByIdAnnonce2) {
        this.id = id;
        this.annonceByIdAnnonce1 = annonceByIdAnnonce1;
        this.annonceByIdAnnonce2 = annonceByIdAnnonce2;
    }
    public Doublant(DoublantId id, Annonce annonceByIdAnnonce1, Annonce annonceByIdAnnonce2, BigDecimal pourcentageTitreDoublant, BigDecimal pourcentageCategorieDoublant, BigDecimal pourcentagePhotoDoublant, BigDecimal pourcentageTexteDoublant) {
       this.id = id;
       this.annonceByIdAnnonce1 = annonceByIdAnnonce1;
       this.annonceByIdAnnonce2 = annonceByIdAnnonce2;
       this.pourcentageTitreDoublant = pourcentageTitreDoublant;
       this.pourcentageCategorieDoublant = pourcentageCategorieDoublant;
       this.pourcentagePhotoDoublant = pourcentagePhotoDoublant;
       this.pourcentageTexteDoublant = pourcentageTexteDoublant;
    }
   
    public DoublantId getId() {
        return this.id;
    }
    
    public void setId(DoublantId id) {
        this.id = id;
    }
    public Annonce getAnnonceByIdAnnonce1() {
        return this.annonceByIdAnnonce1;
    }
    
    public void setAnnonceByIdAnnonce1(Annonce annonceByIdAnnonce1) {
        this.annonceByIdAnnonce1 = annonceByIdAnnonce1;
    }
    public Annonce getAnnonceByIdAnnonce2() {
        return this.annonceByIdAnnonce2;
    }
    
    public void setAnnonceByIdAnnonce2(Annonce annonceByIdAnnonce2) {
        this.annonceByIdAnnonce2 = annonceByIdAnnonce2;
    }
    public BigDecimal getPourcentageTitreDoublant() {
        return this.pourcentageTitreDoublant;
    }
    
    public void setPourcentageTitreDoublant(BigDecimal pourcentageTitreDoublant) {
        this.pourcentageTitreDoublant = pourcentageTitreDoublant;
    }
    public BigDecimal getPourcentageCategorieDoublant() {
        return this.pourcentageCategorieDoublant;
    }
    
    public void setPourcentageCategorieDoublant(BigDecimal pourcentageCategorieDoublant) {
        this.pourcentageCategorieDoublant = pourcentageCategorieDoublant;
    }
    public BigDecimal getPourcentagePhotoDoublant() {
        return this.pourcentagePhotoDoublant;
    }
    
    public void setPourcentagePhotoDoublant(BigDecimal pourcentagePhotoDoublant) {
        this.pourcentagePhotoDoublant = pourcentagePhotoDoublant;
    }
    public BigDecimal getPourcentageTexteDoublant() {
        return this.pourcentageTexteDoublant;
    }
    
    public void setPourcentageTexteDoublant(BigDecimal pourcentageTexteDoublant) {
        this.pourcentageTexteDoublant = pourcentageTexteDoublant;
    }




}


