package model;
// Generated 7 janv. 2020 21:01:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * FavorisId generated by hbm2java
 */
public class FavorisId  implements java.io.Serializable {


     private BigDecimal idUtilisateurConnecte;
     private BigDecimal idAnnonce;
     private String dateFavoris;
     private String heureFavoris;

    public FavorisId() {
    }

    public FavorisId(BigDecimal idUtilisateurConnecte, BigDecimal idAnnonce, String dateFavoris, String heureFavoris) {
       this.idUtilisateurConnecte = idUtilisateurConnecte;
       this.idAnnonce = idAnnonce;
       this.dateFavoris = dateFavoris;
       this.heureFavoris = heureFavoris;
    }
   
    public BigDecimal getIdUtilisateurConnecte() {
        return this.idUtilisateurConnecte;
    }
    
    public void setIdUtilisateurConnecte(BigDecimal idUtilisateurConnecte) {
        this.idUtilisateurConnecte = idUtilisateurConnecte;
    }
    public BigDecimal getIdAnnonce() {
        return this.idAnnonce;
    }
    
    public void setIdAnnonce(BigDecimal idAnnonce) {
        this.idAnnonce = idAnnonce;
    }
    public String getDateFavoris() {
        return this.dateFavoris;
    }
    
    public void setDateFavoris(String dateFavoris) {
        this.dateFavoris = dateFavoris;
    }
    public String getHeureFavoris() {
        return this.heureFavoris;
    }
    
    public void setHeureFavoris(String heureFavoris) {
        this.heureFavoris = heureFavoris;
    }




}


