package model;
// Generated 7 janv. 2020 21:01:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * MaisonVilla generated by hbm2java
 */
public class MaisonVilla  implements java.io.Serializable {


     private BigDecimal idMaisonVilla;
     private Annonce annonce;
     private BigDecimal nbPiecesMaisonVilla;
     private BigDecimal superficieMaisonVilla;
     private BigDecimal prixMetreCarreMaisonVilla;
     private String emplacementMaisonVilla;
     private Set appartements = new HashSet(0);

    public MaisonVilla() {
    }

    public MaisonVilla(Annonce annonce, BigDecimal nbPiecesMaisonVilla, BigDecimal superficieMaisonVilla, BigDecimal prixMetreCarreMaisonVilla, String emplacementMaisonVilla, Set appartements) {
       this.annonce = annonce;
       this.nbPiecesMaisonVilla = nbPiecesMaisonVilla;
       this.superficieMaisonVilla = superficieMaisonVilla;
       this.prixMetreCarreMaisonVilla = prixMetreCarreMaisonVilla;
       this.emplacementMaisonVilla = emplacementMaisonVilla;
       this.appartements = appartements;
    }
   
    public BigDecimal getIdMaisonVilla() {
        return this.idMaisonVilla;
    }
    
    public void setIdMaisonVilla(BigDecimal idMaisonVilla) {
        this.idMaisonVilla = idMaisonVilla;
    }
    public Annonce getAnnonce() {
        return this.annonce;
    }
    
    public void setAnnonce(Annonce annonce) {
        this.annonce = annonce;
    }
    public BigDecimal getNbPiecesMaisonVilla() {
        return this.nbPiecesMaisonVilla;
    }
    
    public void setNbPiecesMaisonVilla(BigDecimal nbPiecesMaisonVilla) {
        this.nbPiecesMaisonVilla = nbPiecesMaisonVilla;
    }
    public BigDecimal getSuperficieMaisonVilla() {
        return this.superficieMaisonVilla;
    }
    
    public void setSuperficieMaisonVilla(BigDecimal superficieMaisonVilla) {
        this.superficieMaisonVilla = superficieMaisonVilla;
    }
    public BigDecimal getPrixMetreCarreMaisonVilla() {
        return this.prixMetreCarreMaisonVilla;
    }
    
    public void setPrixMetreCarreMaisonVilla(BigDecimal prixMetreCarreMaisonVilla) {
        this.prixMetreCarreMaisonVilla = prixMetreCarreMaisonVilla;
    }
    public String getEmplacementMaisonVilla() {
        return this.emplacementMaisonVilla;
    }
    
    public void setEmplacementMaisonVilla(String emplacementMaisonVilla) {
        this.emplacementMaisonVilla = emplacementMaisonVilla;
    }
    public Set getAppartements() {
        return this.appartements;
    }
    
    public void setAppartements(Set appartements) {
        this.appartements = appartements;
    }




}


