package model;
// Generated 7 janv. 2020 21:01:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private BigDecimal idMessage;
     private UtilisateurConnecte utilisateurConnecteByIdUtilConEnvoi;
     private UtilisateurConnecte utilisateurConnecteByIdUtilConRecoi;
     private Chat chat;
     private String contenuMessage;
     private String etatMessage;
     private String modMessage;
     private String dateMessage;
     private String heureMessage;

    public Message() {
    }

    public Message(UtilisateurConnecte utilisateurConnecteByIdUtilConEnvoi, UtilisateurConnecte utilisateurConnecteByIdUtilConRecoi, Chat chat, String contenuMessage, String etatMessage, String dateMessage, String heureMessage) {
       this.utilisateurConnecteByIdUtilConEnvoi = utilisateurConnecteByIdUtilConEnvoi;
       this.utilisateurConnecteByIdUtilConRecoi = utilisateurConnecteByIdUtilConRecoi;
       this.chat = chat;
       this.contenuMessage = contenuMessage;
       this.etatMessage = etatMessage;
       this.dateMessage = dateMessage;
       this.heureMessage = heureMessage;
    }
   
    public BigDecimal getIdMessage() {
        return this.idMessage;
    }
    
    public void setIdMessage(BigDecimal idMessage) {
        this.idMessage = idMessage;
    }
    public UtilisateurConnecte getUtilisateurConnecteByIdUtilConEnvoi() {
        return this.utilisateurConnecteByIdUtilConEnvoi;
    }
    
    public void setUtilisateurConnecteByIdUtilConEnvoi(UtilisateurConnecte utilisateurConnecteByIdUtilConEnvoi) {
        this.utilisateurConnecteByIdUtilConEnvoi = utilisateurConnecteByIdUtilConEnvoi;
    }
    public UtilisateurConnecte getUtilisateurConnecteByIdUtilConRecoi() {
        return this.utilisateurConnecteByIdUtilConRecoi;
    }
    
    public void setUtilisateurConnecteByIdUtilConRecoi(UtilisateurConnecte utilisateurConnecteByIdUtilConRecoi) {
        this.utilisateurConnecteByIdUtilConRecoi = utilisateurConnecteByIdUtilConRecoi;
    }
    public Chat getChat() {
        return this.chat;
    }
    
    public void setChat(Chat chat) {
        this.chat = chat;
    }
    public String getContenuMessage() {
        return this.contenuMessage;
    }
    
    public void setContenuMessage(String contenuMessage) {
        this.contenuMessage = contenuMessage;
    }
    public String getEtatMessage() {
        return this.etatMessage;
    }
    
    public void setEtatMessage(String etatMessage) {
        this.etatMessage = etatMessage;
    }
    public String getDateMessage() {
        return this.dateMessage;
    }
    
    public void setDateMessage(String dateMessage) {
        this.dateMessage = dateMessage;
    }
    public String getHeureMessage() {
        return this.heureMessage;
    }
    
    public void setHeureMessage(String heureMessage) {
        this.heureMessage = heureMessage;
    }

    public String getModMessage() {
        return modMessage;
    }

    public void setModMessage(String modMessage) {
        this.modMessage = modMessage;
    }




}


