package model;
// Generated 7 janv. 2020 21:01:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Modification generated by hbm2java
 */
public class Modification  implements java.io.Serializable {


     private BigDecimal idMod;
     private Annonce annonceOld;
     private Annonce annonceNew;
     private String dateModification;
     private String heureModification;

    public Modification() {
    }

    public Modification(Annonce annonceByIdAnnonceOld, Annonce annonceByIdAnnonceNew, String dateModification, String heureModification) {
       this.annonceOld = annonceOld;
       this.annonceNew = annonceNew;
       this.dateModification = dateModification;
       this.heureModification = heureModification;
    }
   
    public BigDecimal getIdMod() {
        return this.idMod;
    }
    
    public void setIdMod(BigDecimal idMod) {
        this.idMod = idMod;
    }

    public Annonce getAnnonceOld() {
        return annonceOld;
    }

    public void setAnnonceOld(Annonce annonceOld) {
        this.annonceOld = annonceOld;
    }

    public Annonce getAnnonceNew() {
        return annonceNew;
    }

    public void setAnnonceNew(Annonce annonceNew) {
        this.annonceNew = annonceNew;
    }
  
    public String getDateModification() {
        return this.dateModification;
    }
    
    public void setDateModification(String dateModification) {
        this.dateModification = dateModification;
    }
    public String getHeureModification() {
        return this.heureModification;
    }
    
    public void setHeureModification(String heureModification) {
        this.heureModification = heureModification;
    }




}


