package model;
// Generated 7 janv. 2020 21:01:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Moto generated by hbm2java
 */
public class Moto  implements java.io.Serializable {


     private BigDecimal idMoto;
     private Annonce annonce;
     private BigDecimal anneModelMoto;
     private BigDecimal kilometrageMoto;

    public Moto() {
    }

    public Moto(Annonce annonce, BigDecimal anneModelMoto, BigDecimal kilometrageMoto) {
       this.annonce = annonce;
       this.anneModelMoto = anneModelMoto;
       this.kilometrageMoto = kilometrageMoto;
    }
   
    public BigDecimal getIdMoto() {
        return this.idMoto;
    }
    
    public void setIdMoto(BigDecimal idMoto) {
        this.idMoto = idMoto;
    }
    public Annonce getAnnonce() {
        return this.annonce;
    }
    
    public void setAnnonce(Annonce annonce) {
        this.annonce = annonce;
    }
    public BigDecimal getAnneModelMoto() {
        return this.anneModelMoto;
    }
    
    public void setAnneModelMoto(BigDecimal anneModelMoto) {
        this.anneModelMoto = anneModelMoto;
    }
    public BigDecimal getKilometrageMoto() {
        return this.kilometrageMoto;
    }
    
    public void setKilometrageMoto(BigDecimal kilometrageMoto) {
        this.kilometrageMoto = kilometrageMoto;
    }




}


