package model;
// Generated 5 f�vr. 2020 12:24:11 by Hibernate Tools 4.3.1



/**
 * Reclamation generated by hbm2java
 */
public class Reclamation  implements java.io.Serializable {


     private ReclamationId id;
     private UtilisateurConnecte utilisateurConnecte;
     private Employe employe;
     private Annonce annonce;
     private String motifReclamation;
     private String contenuReclamation;
     private String etatReclamation;
     private String dateTrait;
     private String heureTrait;

    public Reclamation() {
    }

	
    public Reclamation(ReclamationId id, UtilisateurConnecte utilisateurConnecte, Annonce annonce) {
        this.id = id;
        this.utilisateurConnecte = utilisateurConnecte;
        this.annonce = annonce;
    }
    public Reclamation(ReclamationId id, UtilisateurConnecte utilisateurConnecte, Employe employe, Annonce annonce, String motifReclamation, String contenuReclamation, String etatReclamation, String dateTrait, String heureTrait) {
       this.id = id;
       this.utilisateurConnecte = utilisateurConnecte;
       this.employe = employe;
       this.annonce = annonce;
       this.motifReclamation = motifReclamation;
       this.contenuReclamation = contenuReclamation;
       this.etatReclamation = etatReclamation;
       this.dateTrait = dateTrait;
       this.heureTrait = heureTrait;
    }
   
    public ReclamationId getId() {
        return this.id;
    }
    
    public void setId(ReclamationId id) {
        this.id = id;
    }
    public UtilisateurConnecte getUtilisateurConnecte() {
        return this.utilisateurConnecte;
    }
    
    public void setUtilisateurConnecte(UtilisateurConnecte utilisateurConnecte) {
        this.utilisateurConnecte = utilisateurConnecte;
    }
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }
    public Annonce getAnnonce() {
        return this.annonce;
    }
    
    public void setAnnonce(Annonce annonce) {
        this.annonce = annonce;
    }
    public String getMotifReclamation() {
        return this.motifReclamation;
    }
    
    public void setMotifReclamation(String motifReclamation) {
        this.motifReclamation = motifReclamation;
    }
    public String getContenuReclamation() {
        return this.contenuReclamation;
    }
    
    public void setContenuReclamation(String contenuReclamation) {
        this.contenuReclamation = contenuReclamation;
    }
    public String getEtatReclamation() {
        return this.etatReclamation;
    }
    
    public void setEtatReclamation(String etatReclamation) {
        this.etatReclamation = etatReclamation;
    }
    public String getDateTrait() {
        return this.dateTrait;
    }
    
    public void setDateTrait(String dateTrait) {
        this.dateTrait = dateTrait;
    }
    public String getHeureTrait() {
        return this.heureTrait;
    }
    
    public void setHeureTrait(String heureTrait) {
        this.heureTrait = heureTrait;
    }




}


