package model;
// Generated 7 janv. 2020 21:01:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ReclamationId generated by hbm2java
 */
public class ReclamationId  implements java.io.Serializable {


     private BigDecimal idUtilisateurConnecte;
     private BigDecimal idAnnonce;
     private String dateReclamation;
     private String heureReclamation;

    public ReclamationId() {
    }

    public ReclamationId(BigDecimal idUtilisateurConnecte, BigDecimal idAnnonce, String dateReclamation, String heureReclamation) {
       this.idUtilisateurConnecte = idUtilisateurConnecte;
       this.idAnnonce = idAnnonce;
       this.dateReclamation = dateReclamation;
       this.heureReclamation = heureReclamation;
    }
   
    public BigDecimal getIdUtilisateurConnecte() {
        return this.idUtilisateurConnecte;
    }
    
    public void setIdUtilisateurConnecte(BigDecimal idUtilisateurConnecte) {
        this.idUtilisateurConnecte = idUtilisateurConnecte;
    }
    public BigDecimal getIdAnnonce() {
        return this.idAnnonce;
    }
    
    public void setIdAnnonce(BigDecimal idAnnonce) {
        this.idAnnonce = idAnnonce;
    }
    public String getDateReclamation() {
        return this.dateReclamation;
    }
    
    public void setDateReclamation(String dateReclamation) {
        this.dateReclamation = dateReclamation;
    }
    public String getHeureReclamation() {
        return this.heureReclamation;
    }
    
    public void setHeureReclamation(String heureReclamation) {
        this.heureReclamation = heureReclamation;
    }




}


