package model;
// Generated 7 janv. 2020 21:01:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TerrainFerme generated by hbm2java
 */
public class TerrainFerme  implements java.io.Serializable {


     private BigDecimal idTerrainFerme;
     private AutreImmobilier autreImmobilier;
     private String zoningTerrainFerme;

    public TerrainFerme() {
    }

    public TerrainFerme(AutreImmobilier autreImmobilier, String zoningTerrainFerme) {
       this.autreImmobilier = autreImmobilier;
       this.zoningTerrainFerme = zoningTerrainFerme;
    }
   
    public BigDecimal getIdTerrainFerme() {
        return this.idTerrainFerme;
    }
    
    public void setIdTerrainFerme(BigDecimal idTerrainFerme) {
        this.idTerrainFerme = idTerrainFerme;
    }
    public AutreImmobilier getAutreImmobilier() {
        return this.autreImmobilier;
    }
    
    public void setAutreImmobilier(AutreImmobilier autreImmobilier) {
        this.autreImmobilier = autreImmobilier;
    }
    public String getZoningTerrainFerme() {
        return this.zoningTerrainFerme;
    }
    
    public void setZoningTerrainFerme(String zoningTerrainFerme) {
        this.zoningTerrainFerme = zoningTerrainFerme;
    }




}


