package model;
// Generated 7 janv. 2020 21:01:58 by Hibernate Tools 4.3.1


import dao.AnnonceDao;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * UtilisateurConnecte generated by hbm2java
 */
public class UtilisateurConnecte  implements java.io.Serializable {


     private BigDecimal idUtilisateurConnecte;
     private String nom;
     private String etatcompte;
     private String emailUtilConnecte;
     private String telUtilConnecte;
     private String villeUtilConnecte;
     private String telVisiblUtilConnecte;
     private String passwordUtilConnecte;
     private String noteEmailUtilConnecte;
     private String noteTelUtilConnecte;
     private String phProfil;
     private String degreNoteTELUtilConnecte ;
     private String degreNoteEmailUtilConnecte;
     private Set chatsForIdUtilisateurConnecte1 = new HashSet(0);
     private Set favorises = new HashSet(0);
     private Set chatsForIdUtilisateurConnecte = new HashSet(0);
     private Set messagesForIdUtilConEnvoi = new HashSet(0);
     private Set messagesForIdUtilConRecoi = new HashSet(0);
     private Set actionUsers = new HashSet(0);
     private Set annonces = new HashSet(0);
     private Set reclamations = new HashSet(0);
     
      private List<String>Ips=new ArrayList<>();

    public UtilisateurConnecte() {
    }

    public List<String> getIps() {
        AnnonceDao ad=new AnnonceDao();
        Ips=ad.getIpsByUser(this);
        return Ips;
    }

    public void setIps(List<String> Ips) {
        this.Ips = Ips;
    }

    public UtilisateurConnecte(String nom, String etatcompte, String emailUtilConnecte, String telUtilConnecte, String villeUtilConnecte, String telVisiblUtilConnecte, String passwordUtilConnecte, String noteEmailUtilConnecte, String noteTelUtilConnecte, String phProfil, Set chatsForIdUtilisateurConnecte1, Set favorises, Set chatsForIdUtilisateurConnecte, Set messagesForIdUtilConEnvoi, Set messagesForIdUtilConRecoi, Set actionUsers, Set annonces, Set reclamations) {
       this.nom = nom;
       this.etatcompte = etatcompte;
       this.emailUtilConnecte = emailUtilConnecte;
       this.telUtilConnecte = telUtilConnecte;
       this.villeUtilConnecte = villeUtilConnecte;
       this.telVisiblUtilConnecte = telVisiblUtilConnecte;
       this.passwordUtilConnecte = passwordUtilConnecte;
       this.noteEmailUtilConnecte = noteEmailUtilConnecte;
       this.noteTelUtilConnecte = noteTelUtilConnecte;
       this.phProfil = phProfil;
       this.chatsForIdUtilisateurConnecte1 = chatsForIdUtilisateurConnecte1;
       this.favorises = favorises;
       this.chatsForIdUtilisateurConnecte = chatsForIdUtilisateurConnecte;
       this.messagesForIdUtilConEnvoi = messagesForIdUtilConEnvoi;
       this.messagesForIdUtilConRecoi = messagesForIdUtilConRecoi;
       this.actionUsers = actionUsers;
       this.annonces = annonces;
       this.reclamations = reclamations;
    }
   
    public BigDecimal getIdUtilisateurConnecte() {
        return this.idUtilisateurConnecte;
    }
    
    public void setIdUtilisateurConnecte(BigDecimal idUtilisateurConnecte) {
        this.idUtilisateurConnecte = idUtilisateurConnecte;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getEtatcompte() {
        return this.etatcompte;
    }
    
    public void setEtatcompte(String etatcompte) {
        this.etatcompte = etatcompte;
    }
    public String getEmailUtilConnecte() {
        return this.emailUtilConnecte;
    }
    
    public void setEmailUtilConnecte(String emailUtilConnecte) {
        this.emailUtilConnecte = emailUtilConnecte;
    }
    public String getTelUtilConnecte() {
        return this.telUtilConnecte;
    }
    
    public void setTelUtilConnecte(String telUtilConnecte) {
        this.telUtilConnecte = telUtilConnecte;
    }
    public String getVilleUtilConnecte() {
        return this.villeUtilConnecte;
    }

    public String getDegreNoteTELUtilConnecte() {
        return degreNoteTELUtilConnecte;
    }

    public void setDegreNoteTELUtilConnecte(String degreNoteTELUtilConnecte) {
        this.degreNoteTELUtilConnecte = degreNoteTELUtilConnecte;
    }

    public String getDegreNoteEmailUtilConnecte() {
        return degreNoteEmailUtilConnecte;
    }

    public void setDegreNoteEmailUtilConnecte(String degreNoteEmailUtilConnecte) {
        this.degreNoteEmailUtilConnecte = degreNoteEmailUtilConnecte;
    }
    
    public void setVilleUtilConnecte(String villeUtilConnecte) {
        this.villeUtilConnecte = villeUtilConnecte;
    }
    public String getTelVisiblUtilConnecte() {
        return this.telVisiblUtilConnecte;
    }
    
    public void setTelVisiblUtilConnecte(String telVisiblUtilConnecte) {
        this.telVisiblUtilConnecte = telVisiblUtilConnecte;
    }
    public String getPasswordUtilConnecte() {
        return this.passwordUtilConnecte;
    }
    
    public void setPasswordUtilConnecte(String passwordUtilConnecte) {
        this.passwordUtilConnecte = passwordUtilConnecte;
    }
    public String getNoteEmailUtilConnecte() {
        return this.noteEmailUtilConnecte;
    }
    
    public void setNoteEmailUtilConnecte(String noteEmailUtilConnecte) {
        this.noteEmailUtilConnecte = noteEmailUtilConnecte;
    }
    public String getNoteTelUtilConnecte() {
        return this.noteTelUtilConnecte;
    }
    
    public void setNoteTelUtilConnecte(String noteTelUtilConnecte) {
        this.noteTelUtilConnecte = noteTelUtilConnecte;
    }
    public String getPhProfil() {
        return this.phProfil;
    }
    
    public void setPhProfil(String phProfil) {
        this.phProfil = phProfil;
    }
    public Set getChatsForIdUtilisateurConnecte1() {
        return this.chatsForIdUtilisateurConnecte1;
    }
    
    public void setChatsForIdUtilisateurConnecte1(Set chatsForIdUtilisateurConnecte1) {
        this.chatsForIdUtilisateurConnecte1 = chatsForIdUtilisateurConnecte1;
    }
    public Set getFavorises() {
        return this.favorises;
    }
    
    public void setFavorises(Set favorises) {
        this.favorises = favorises;
    }
    public Set getChatsForIdUtilisateurConnecte() {
        return this.chatsForIdUtilisateurConnecte;
    }
    
    public void setChatsForIdUtilisateurConnecte(Set chatsForIdUtilisateurConnecte) {
        this.chatsForIdUtilisateurConnecte = chatsForIdUtilisateurConnecte;
    }
    public Set getMessagesForIdUtilConEnvoi() {
        return this.messagesForIdUtilConEnvoi;
    }
    
    public void setMessagesForIdUtilConEnvoi(Set messagesForIdUtilConEnvoi) {
        this.messagesForIdUtilConEnvoi = messagesForIdUtilConEnvoi;
    }
    public Set getMessagesForIdUtilConRecoi() {
        return this.messagesForIdUtilConRecoi;
    }
    
    public void setMessagesForIdUtilConRecoi(Set messagesForIdUtilConRecoi) {
        this.messagesForIdUtilConRecoi = messagesForIdUtilConRecoi;
    }
    public Set getActionUsers() {
        return this.actionUsers;
    }
    
    public void setActionUsers(Set actionUsers) {
        this.actionUsers = actionUsers;
    }
    public Set getAnnonces() {
        return this.annonces;
    }
    
    public void setAnnonces(Set annonces) {
        this.annonces = annonces;
    }
    public Set getReclamations() {
        return this.reclamations;
    }
    
    public void setReclamations(Set reclamations) {
        this.reclamations = reclamations;
    }




}


