package model;
// Generated 7 janv. 2020 21:01:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * VehiculeProfessionnel generated by hbm2java
 */
public class VehiculeProfessionnel  implements java.io.Serializable {


     private BigDecimal idVehiculeProfessionnel;
     private Voiture voiture;
     private String sousCatVehiculeProf;

    public VehiculeProfessionnel() {
    }

    public VehiculeProfessionnel(Voiture voiture, String sousCatVehiculeProf) {
       this.voiture = voiture;
       this.sousCatVehiculeProf = sousCatVehiculeProf;
    }
   
    public BigDecimal getIdVehiculeProfessionnel() {
        return this.idVehiculeProfessionnel;
    }
    
    public void setIdVehiculeProfessionnel(BigDecimal idVehiculeProfessionnel) {
        this.idVehiculeProfessionnel = idVehiculeProfessionnel;
    }
    public Voiture getVoiture() {
        return this.voiture;
    }
    
    public void setVoiture(Voiture voiture) {
        this.voiture = voiture;
    }
    public String getSousCatVehiculeProf() {
        return this.sousCatVehiculeProf;
    }
    
    public void setSousCatVehiculeProf(String sousCatVehiculeProf) {
        this.sousCatVehiculeProf = sousCatVehiculeProf;
    }




}


