package model;
// Generated 7 janv. 2020 21:01:58 by Hibernate Tools 4.3.1


import dao.VehiculeProfessionnelDao;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Voiture generated by hbm2java
 */
public class Voiture  implements java.io.Serializable {


     private BigDecimal idVoiture;
     private Annonce annonce;
     private String marqueVoiture;
     private String modeleVoiture;
     private String typeCarburantVoiture;
     private BigDecimal anneeModeleVoiture;
     private BigDecimal kilometrage;
     private String puissanceFiscaleVoiture;
     private Set vehiculeProfessionnels = new HashSet(0);
     private VehiculeProfessionnel vehiculeProfessionnel;

    public Voiture() {
    }

    public Voiture(Annonce annonce, String marqueVoiture, String modeleVoiture, String typeCarburantVoiture, BigDecimal anneeModeleVoiture, BigDecimal kilometrage, String puissanceFiscaleVoiture, Set vehiculeProfessionnels) {
       this.annonce = annonce;
       this.marqueVoiture = marqueVoiture;
       this.modeleVoiture = modeleVoiture;
       this.typeCarburantVoiture = typeCarburantVoiture;
       this.anneeModeleVoiture = anneeModeleVoiture;
       this.kilometrage = kilometrage;
       this.puissanceFiscaleVoiture = puissanceFiscaleVoiture;
       this.vehiculeProfessionnels = vehiculeProfessionnels;
    }

    public VehiculeProfessionnel getVehiculeProfessionnel() {
         VehiculeProfessionnelDao vd=new VehiculeProfessionnelDao();
        vehiculeProfessionnel=vd.getvehiculeProfessionnelByVoiture(this);
        
        return vehiculeProfessionnel;
    }

    public void setVehiculeProfessionnel(VehiculeProfessionnel vehiculeProfessionnel) {
        this.vehiculeProfessionnel = vehiculeProfessionnel;
    }
   
    public BigDecimal getIdVoiture() {
        return this.idVoiture;
    }
    
    public void setIdVoiture(BigDecimal idVoiture) {
        this.idVoiture = idVoiture;
    }
    public Annonce getAnnonce() {
        return this.annonce;
    }
    
    public void setAnnonce(Annonce annonce) {
        this.annonce = annonce;
    }
    public String getMarqueVoiture() {
        return this.marqueVoiture;
    }
    
    public void setMarqueVoiture(String marqueVoiture) {
        this.marqueVoiture = marqueVoiture;
    }
    public String getModeleVoiture() {
        return this.modeleVoiture;
    }
    
    public void setModeleVoiture(String modeleVoiture) {
        this.modeleVoiture = modeleVoiture;
    }
    public String getTypeCarburantVoiture() {
        return this.typeCarburantVoiture;
    }
    
    public void setTypeCarburantVoiture(String typeCarburantVoiture) {
        this.typeCarburantVoiture = typeCarburantVoiture;
    }
    public BigDecimal getAnneeModeleVoiture() {
        return this.anneeModeleVoiture;
    }
    
    public void setAnneeModeleVoiture(BigDecimal anneeModeleVoiture) {
        this.anneeModeleVoiture = anneeModeleVoiture;
    }
    public BigDecimal getKilometrage() {
        return this.kilometrage;
    }
    
    public void setKilometrage(BigDecimal kilometrage) {
        this.kilometrage = kilometrage;
    }
    public String getPuissanceFiscaleVoiture() {
        return this.puissanceFiscaleVoiture;
    }
    
    public void setPuissanceFiscaleVoiture(String puissanceFiscaleVoiture) {
        this.puissanceFiscaleVoiture = puissanceFiscaleVoiture;
    }
    public Set getVehiculeProfessionnels() {
        return this.vehiculeProfessionnels;
    }
    
    public void setVehiculeProfessionnels(Set vehiculeProfessionnels) {
        this.vehiculeProfessionnels = vehiculeProfessionnels;
    }




}


